# Generated by Django 5.1.6 on 2025-05-12 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0006_medecin_iban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheevenement',
            name='frais_dossier',
            field=models.IntegerField(default=0, verbose_name='Frais de dossier = 3000'),
        ),
        migrations.AlterField(
            model_name='ficheevenement',
            name='honoraire_cempn',
            field=models.IntegerField(default=0, verbose_name='CEMPN = 10000'),
        ),
        migrations.AlterField(
            model_name='ficheevenement',
            name='honoraire_cs_labo',
            field=models.IntegerField(default=0, verbose_name='Labo AMJ = 5529'),
        ),
        migrations.AlterField(
            model_name='ficheevenement',
            name='honoraire_cs_lbx',
            field=models.IntegerField(default=0, verbose_name='Labstix = 2337'),
        ),
        migrations.AlterField(
            model_name='ficheevenement',
            name='honoraire_cs_oph',
            field=models.IntegerField(default=0, verbose_name='OPH = 10600'),
        ),
        migrations.AlterField(
            model_name='ficheevenement',
            name='honoraire_cs_orl',
            field=models.IntegerField(default=0, verbose_name='ORL = 13250'),
        ),
        migrations.AlterField(
            model_name='ficheevenement',
            name='honoraire_cs_radio',
            field=models.IntegerField(default=0, verbose_name='Radio = 8400'),
        ),
        migrations.AlterField(
            model_name='ficheevenement',
            name='honoraire_cs_toxique',
            field=models.IntegerField(default=0, verbose_name='Toxique = 16644'),
        ),
        migrations.AlterField(
            model_name='personnelnavigant',
            name='dn',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_dn', message='Attention Christian, le dn doit contenir exactement 7 chiffres, et aucun autre symbole, ou lettre.', regex='^\\d{7}$')]),
        ),
    ]
