# Generated by Django 5.1.6 on 2025-12-15 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0007_alter_ficheevenement_frais_dossier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheevenement',
            name='frais_dossier',
            field=models.IntegerField(default=3000, verbose_name='Frais de dossier = 3000'),
        ),
        migrations.AlterField(
            model_name='ficheevenement',
            name='honoraire_cs_labo',
            field=models.IntegerField(default=0, verbose_name='Labo AMJ = 7122'),
        ),
        migrations.AlterField(
            model_name='ficheevenement',
            name='honoraire_cs_toxique',
            field=models.IntegerField(default=0, verbose_name='Toxique = 17442'),
        ),
        migrations.CreateModel(
            name='MedecinInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('emission_date', models.DateField()),
                ('total_brut', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_redevance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_generales', to='expertise.medecin')),
            ],
            options={
                'ordering': ['-emission_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedecinInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_code', models.CharField(max_length=30)),
                ('act_label', models.CharField(max_length=120)),
                ('date_acte', models.DateField()),
                ('patient_nom', models.CharField(max_length=120)),
                ('patient_prenom', models.CharField(max_length=120)),
                ('facture_no', models.CharField(blank=True, max_length=50, null=True)),
                ('montant_brut', models.DecimalField(decimal_places=2, max_digits=12)),
                ('redevance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_medicaux', to='expertise.ficheevenement')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='expertise.medecininvoice')),
            ],
            options={
                'ordering': ['date_acte', 'pk'],
                'unique_together': {('evenement', 'act_code')},
            },
        ),
    ]
